language: node_js
node_js: node
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: ltQQ0JnK2G/wYuEAdxv53k+NosdR39byXnqqMpGnfiWXvYDLu+fHkzMV4hd+k/9ZdPn8z/Wy2TYPGWK0/eJywxGyqS/6rpJE0Xhpyw4Nl5LDp8i1arQUoCXyQep06e0mky62So2YO1Ki2RMdZ5mn1baP5KbWPGeDBSinFCTRcO2BeXgS1n7d/Wk8RfqtGgYgjSMvLt/sJ6ocr6Ygz0Wc5Mu9F/N7zX/snfCIv6Cwa1wqD+91XjugAo1kfoWQDVzhtuzy9JZ7CpMcXgjE9xxJE93Aa+Ai/pw3J8v9SY+pIIrwEuxWINW57XuXo2ZsCLwNlYM7BQ4RE82d9EPpKaSYV9YCyCyjnxSG7oZHdjY2WjvlCMUblYlqjw0hZomLvrECkHdnTOGHvUMWWezMeGwKAOQdhwT+T5/+ouBTvxhbCtXiqLsma2ftHwUBPKZ9HYq8xJ5mvVGAMcHM5+IrHctRjza2TDeYTLfyqzq9lNeqKlLgbDktDVeCbHKKYvyAYbaTmBWrGiG8Juc1gJ1B5HfF8lSBysE139GPz1dTDQJTUJm5vZuWpnPS3CeObXS5NNEWzE2lcTwzStApdO39yj4L5miTnzmfuXdiETxG2DB+jj715J5dY17cphf+xbYB/uUgTZfVM1bzG1AmD5aSt3tu9ffRbXABaBhk4Wax37WihcE=
  app: mighty-dusk-54682
  on:
    repo: aaltamirano1/node-shopping-list-integration-tests
