language: node_js
node_js: node
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: ACJyzpTTNyXutQS1CUwmZn/qPWxrdEdkvgDUN3+ms//I4xNLkESfOg1pMnoFwkZx6UlNehlLVX4uRGmtRstjBlU/k07YDzupZ4JH1j1CHT75LaidZ3MJdekZAcDJNeg/XBjZnoKVqhf/HnllMskjBkJ5OJf51lKTsmI+IURoRUq92dtO7yO5Jv1U8j6MeazO32XNi44QdiVyDPK5oySN4qTlUKat8dlrBump8wErOWAQJM/DofiUBM6wVyZJN7SHtET5UVzlxYXjZn0XgeJHe2cBgNI3KbkO5QcOeA42SXUgBUsgC8R6Kc+1x44ReS0CCzkth/u66rcJJqX4iwH5UpzZaFM971Z6VPc/j+nq31lG7u8fxCsR7Ypi0qvPf5hQCyTQm1QwwcPV0HL59w3tgeLuvZIE4LLm6bkkm5mbclB+wUf/GJ35nASG6F3Cz4v0xU5thGfpzxUDsCL1WFAUhoGZ4efCDIcGZUI6uVHK/+AzMU/nmAlzRqCNaqRkik26aQauuMRBZA2fvVRxBKuqZ3mihRyuHqT9jVcpwXKiWFkFohVblVb+VT+ubm+v7TVBpfJywZZjUJwRnpLeEVCCSfDNDeEC6gxj5otyDDdmEe128h6S5a2M9cC0BukUO2P/JPcvbNnv/FyxipOAfEk9dJ49LKNs1Dzjx3z/SmPUyT0=
  app: mighty-dusk-54682
  on:
    repo: aaltamirano1/node-shopping-list-integration-tests
